### ISSUE TITLE
Descrever árvore de decisão 

### ISSUE THREAD

**Issue by VitorRicchetti** [antoniocmf/365destinos#5]
Descrever as duas árvores de decisão e como elas irão funcionar.

Anexar imagem da estrutura da árvore de decisão feita pelo Vitor.

**Comment by antoniocmf** [comment]
Arquivo:

https://docs.google.com/document/d/1mcag-Z8HnKsGCZUP5tQUB63LbIVB2vcy8ecymtgQqMM/edit
